name: Run Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=calculator --cov-report=term-missing --cov-report=html

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4  # Use v4 for stability
        with:
          name: coverage-report
          path: htmlcov  # Upload the whole htmlcov folder
                # Step 4: Run tests and generate logs
      - name: Run tests and generate logs
        run: |
          mkdir -p test-logs  # Create a directory to store logs
          pytest --maxfail=1 --disable-warnings --capture=no > test-logs/test_run_log.txt  # Redirect test output to the log file

      # Step 5: Upload the log files as artifacts
      - name: Upload test run logs
        uses: actions/upload-artifact@v2
        with:
          name: test-logs  # Artifact name
          path: test-logs/test_run_log.txt  # Path to the log file
